/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "2.6.6"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.vaadin.com/vaadin-prereleases/")
    }

    maven {
        url = uri("https://maven.vaadin.com/vaadin-addons")
    }
}

dependencies {
    implementation("dev.hilla:hilla:1.0.4")
    implementation("dev.hilla:hilla-spring-boot-starter:1.0.4")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.6.6")
    implementation("org.springframework.boot:spring-boot-devtools:2.6.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.6")
    testImplementation("com.vaadin:vaadin-testbench:23.0.4")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("io.github.bonigarcia:webdrivermanager:5.0.3")
}

group = "com.example.application"
version = "1.0-SNAPSHOT"
description = "hilla-app"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
